### ISSUE TITLE
Online doesn't work

### ISSUE THREAD

**Issue by ghost** [palu3492/art-wars#2]
If i click Play Online it doesn't do anything.
![image](https://user-images.githubusercontent.com/66672754/101359298-5a8a5180-389c-11eb-922a-8c65aaf338bf.png)

**Comment by palu3492** [comment]
Okay, that's odd. My first thought is JavaScript isn't working on your device. I'll need some more details to troubleshoot the problem. If you could answer these questions, that would be great.
- What operating system are you using?
- Are you on mobile or desktop?
- What web browser are you using?
- Is JavaScript enabled?

**Comment by ghost** [comment]
Okay, im using windows, on my laptop, in google, with js enabled.

But it could be that im hosting the server wrong or something.

**Comment by palu3492** [comment]
I didn't realize you were running it locally. It's probably a TLS/SSL issue because you're running it on localhost. Can you provide me the output from the Chrome dev tools console?

**Comment by ghost** [comment]
whait what, it works fine now on my localhost. idk how but its done
Thanks for help
